/*
 * Copyright (C) 2015 ghots
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.zacapalug.veaxml.gui;

import org.zacapalug.veaxml.gui.componentes.PnlPanelDeTrabajo;
import org.zacapalug.veaxml.gui.componentes.PnlAreaDeTrabajo;

/**
 *
 * @author ghots
 */
public class PanelInicio extends PnlPanelDeTrabajo
{

    /**
     * Creates new form PanelInicio
     * @param panelTabs
     */
    public PanelInicio(PnlAreaDeTrabajo panelTabs)
    {
        super(panelTabs);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPublicidad = new javax.swing.JPanel();
        pnlPublicidadA = new javax.swing.JPanel();
        pnlPublicidadB = new javax.swing.JPanel();
        pnlPublicidadC = new javax.swing.JPanel();
        pnlInformacion = new javax.swing.JPanel();

        pnlPublicidadA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlPublicidadA.setPreferredSize(new java.awt.Dimension(287, 2));

        javax.swing.GroupLayout pnlPublicidadALayout = new javax.swing.GroupLayout(pnlPublicidadA);
        pnlPublicidadA.setLayout(pnlPublicidadALayout);
        pnlPublicidadALayout.setHorizontalGroup(
            pnlPublicidadALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        pnlPublicidadALayout.setVerticalGroup(
            pnlPublicidadALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        pnlPublicidadB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlPublicidadB.setPreferredSize(new java.awt.Dimension(287, 2));

        javax.swing.GroupLayout pnlPublicidadBLayout = new javax.swing.GroupLayout(pnlPublicidadB);
        pnlPublicidadB.setLayout(pnlPublicidadBLayout);
        pnlPublicidadBLayout.setHorizontalGroup(
            pnlPublicidadBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );
        pnlPublicidadBLayout.setVerticalGroup(
            pnlPublicidadBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlPublicidadC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlPublicidadC.setPreferredSize(new java.awt.Dimension(287, 2));

        javax.swing.GroupLayout pnlPublicidadCLayout = new javax.swing.GroupLayout(pnlPublicidadC);
        pnlPublicidadC.setLayout(pnlPublicidadCLayout);
        pnlPublicidadCLayout.setHorizontalGroup(
            pnlPublicidadCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        pnlPublicidadCLayout.setVerticalGroup(
            pnlPublicidadCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPublicidadLayout = new javax.swing.GroupLayout(pnlPublicidad);
        pnlPublicidad.setLayout(pnlPublicidadLayout);
        pnlPublicidadLayout.setHorizontalGroup(
            pnlPublicidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPublicidadLayout.createSequentialGroup()
                .addComponent(pnlPublicidadA, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPublicidadB, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPublicidadC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPublicidadLayout.setVerticalGroup(
            pnlPublicidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPublicidadA, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
            .addComponent(pnlPublicidadB, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
            .addComponent(pnlPublicidadC, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        pnlInformacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlInformacionLayout = new javax.swing.GroupLayout(pnlInformacion);
        pnlInformacion.setLayout(pnlInformacionLayout);
        pnlInformacionLayout.setHorizontalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        pnlInformacionLayout.setVerticalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPublicidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPublicidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JPanel pnlPublicidad;
    private javax.swing.JPanel pnlPublicidadA;
    private javax.swing.JPanel pnlPublicidadB;
    private javax.swing.JPanel pnlPublicidadC;
    // End of variables declaration//GEN-END:variables
}
